/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTutorRouteImport } from './routes/_authenticated/tutor'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedExplainRouteImport } from './routes/_authenticated/explain'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedTopicsSlugRouteImport } from './routes/_authenticated/topics.$slug'
import { Route as AuthenticatedProblemsSlugRouteImport } from './routes/_authenticated/problems.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorRoute = AuthenticatedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplainRoute = AuthenticatedExplainRouteImport.update({
  id: '/explain',
  path: '/explain',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTopicsSlugRoute = AuthenticatedTopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsSlugRoute =
  AuthenticatedProblemsSlugRouteImport.update({
    id: '/problems/$slug',
    path: '/problems/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explain': typeof AuthenticatedExplainRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/problems/$slug': typeof AuthenticatedProblemsSlugRoute
  '/topics/$slug': typeof AuthenticatedTopicsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explain': typeof AuthenticatedExplainRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tutor': typeof AuthenticatedTutorRoute
  '/problems/$slug': typeof AuthenticatedProblemsSlugRoute
  '/topics/$slug': typeof AuthenticatedTopicsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explain': typeof AuthenticatedExplainRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tutor': typeof AuthenticatedTutorRoute
  '/_authenticated/problems/$slug': typeof AuthenticatedProblemsSlugRoute
  '/_authenticated/topics/$slug': typeof AuthenticatedTopicsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/analytics'
    | '/dashboard'
    | '/explain'
    | '/profile'
    | '/roadmap'
    | '/settings'
    | '/tutor'
    | '/problems/$slug'
    | '/topics/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/analytics'
    | '/dashboard'
    | '/explain'
    | '/profile'
    | '/roadmap'
    | '/settings'
    | '/tutor'
    | '/problems/$slug'
    | '/topics/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/explain'
    | '/_authenticated/profile'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/tutor'
    | '/_authenticated/problems/$slug'
    | '/_authenticated/topics/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutor': {
      id: '/_authenticated/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof AuthenticatedTutorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explain': {
      id: '/_authenticated/explain'
      path: '/explain'
      fullPath: '/explain'
      preLoaderRoute: typeof AuthenticatedExplainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topics/$slug': {
      id: '/_authenticated/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof AuthenticatedTopicsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems/$slug': {
      id: '/_authenticated/problems/$slug'
      path: '/problems/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof AuthenticatedProblemsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExplainRoute: typeof AuthenticatedExplainRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTutorRoute: typeof AuthenticatedTutorRoute
  AuthenticatedProblemsSlugRoute: typeof AuthenticatedProblemsSlugRoute
  AuthenticatedTopicsSlugRoute: typeof AuthenticatedTopicsSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExplainRoute: AuthenticatedExplainRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTutorRoute: AuthenticatedTutorRoute,
  AuthenticatedProblemsSlugRoute: AuthenticatedProblemsSlugRoute,
  AuthenticatedTopicsSlugRoute: AuthenticatedTopicsSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
